version: '3.9'

services:
  database:
    image: mysql:8.0.28-oracle
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - published: 3306
        target: 3306
        protocol: tcp

  redis:
    image: redis:6.2.6-alpine
